# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker


#trigger:
#- '*'

#resources:
#- repo: self

#variables:
#  tag: '$(Build.BuildId)'

#stages:
#- stage: Build
#  displayName: Build image
#  jobs:
#  - job: Build
#    displayName: Build
#    pool:
#      vmImage: ubuntu-latest
#    steps:
#    - task: Docker@2
#      displayName: Build an image
#      inputs:
#        command: build
#        dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
#        tags: |
#          $(tag)

#    - task: PublishBuildArtifacts@1
#      displayName: 'Publish Artifact'
#      inputs:
#        PathtoPublish: '$(build.artifactstagingdirectory)'


# Docker
# Build a Docker image
# https://learn.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- '*'

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - bash: |
        docker build -t hlbuildimage -f Dockerfile .
        echo "------"
        docker save hlbuildimage > $(Build.ArtifactStagingDirectory)/docker_image.tar
        echo "------"
      displayName: Build high-level Azure Sphere application in a container
    - task: PublishBuildArtifacts@1
      displayName: Publish build artifacts
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)/docker_image.tar'
        ArtifactName: 'docker_image'
        publishLocation: 'Container'

