# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker


#trigger:
#- '*'

#resources:
#- repo: self

#variables:
#  tag: '$(Build.BuildId)'

#stages:
#- stage: Build
#  displayName: Build image
#  jobs:
#  - job: Build
#    displayName: Build
#    pool:
#      vmImage: ubuntu-latest
#    steps:
#    - task: Docker@2
#      displayName: Build an image
#      inputs:
#        command: build
#        dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
#        tags: |
#          $(tag)

#    - task: PublishBuildArtifacts@1
#      displayName: 'Publish Artifact'
#      inputs:
#        PathtoPublish: '$(build.artifactstagingdirectory)'


# Docker
# Build a Docker image
# https://learn.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- '*'

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - bash: |
        docker build -t hlbuildimage -f Dockerfile .
        docker save hlbuildimage > $(Build.ArtifactStagingDirectory)/docker_image.tar
        az devops login --organization https://dev.azure.com/yh8512/
        az artifacts universal publish --organization https://dev.azure.com/yh8512/ --project="TEST_JuiceShop" --scope project --feed test_feed --name JuiceShopDokerImage --version 0.0.1 --description "Test Docker Imange" --path '$(Build.ArtifactStagingDirectory)/docker_image.tar'

#    - task: PublishBuildArtifacts@1
#      displayName: Publish build artifacts
#      inputs:
#        PathtoPublish: '$(Build.ArtifactStagingDirectory)/docker_image.tar'
#        ArtifactName: 'docker_image'
#        publishLocation: 'Container'

